# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: true

#scheme: Muse
#scheme: Mist
# scheme: Pisces
scheme: Gemini

darkmode: true

menu_settings:
  badges: true

menu:
  home: / || fa fa-home
  # about: /about/ || fa fa-user
  # tags: /tags/ || fa fa-tags
  # categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat
  Docs:
    default: /docs/Docs.md || fa fa-book
    # Getting Started:
    #   default: /getting-started/ || fa fa-flag
    #   Installation: /installation.html || fa fa-download
    #   Configuration: /configuration.html || fa fa-wrench
    # Third Party Services:
    #   default: /third-party-services/ || fa fa-puzzle-piece
    #   Math Equations: /math-equations.html || fa fa-square-root-alt
    #   Comment Systems: /comments.html || fa fa-comment-alt